# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0256eac48a92e8eef21569a7ab950226f2be21049d9815111c2706dc5183b7d24cd6ceb94f4f56d3d2188453ef75205bf27607481bd5adae1cce7ddad4557f1b

test:
  secret_key_base: ca4624e95e658fc1d8cc6197186914040f5f051bd8e328cd8d284a64c371d533fd3cd28ee534300a7b5f3c504fe798ae16760d8879042b523cda60853314cc94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
